altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  dda487bc-6fe8-4e39-bd87-bdf8f0ad9a4e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-18T02:53:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ed8f4ce3-3113-4a5f-9bb4-32218628190e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 018409f3-9d5a-49dc-b27e-a1ab7a800827
        userCondition: null
fs: yyy
handle: xxx
name: xxx
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
